services:
  db_votacao:
    container_name: db_votacao
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement=all -p 5433
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_votacao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5433